apiVersion: v1
kind: Service
metadata:
  name: ordercollection-service
spec:
  selector:
    app: order-collection-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

